-- MySQL Script generated by MySQL Workbench
-- qua 21 out 2020 15:33:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema she
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `she` ;

-- -----------------------------------------------------
-- Schema she
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `she` ;
USE `she` ;

-- -----------------------------------------------------
-- Table `she`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `turno` INT NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `info_cadastro` VARCHAR(100) NULL DEFAULT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `curso_id` INT NOT NULL,
  `administrador_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `curso_id` (`curso_id` ASC) VISIBLE,
  INDEX `administrador_id` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `aluno_ibfk_1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `she`.`curso` (`id`),
  CONSTRAINT `aluno_ibfk_2`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `she`.`administrador` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `max_horas` INT NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`aluno_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`aluno_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `horas_registradas` TIME NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `arquivo` VARCHAR(255) NULL DEFAULT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aluno_id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  `administrador_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `aluno_id`, `atividade_id`),
  INDEX `atividade_id` (`atividade_id` ASC) VISIBLE,
  INDEX `aluno_id` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `aluno_atividade_ibfk_1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `she`.`atividade` (`id`),
  CONSTRAINT `aluno_atividade_ibfk_2`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `she`.`aluno` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO curso (nome, sigla, data_registro) VALUES ('Sistema da Informação', 'SI', '2020-01-01 00:00:00');
INSERT INTO curso (nome, sigla, data_registro) VALUES ('Gestão Ambiental', 'GA', '2020-01-01 00:00:00');