-- MySQL Script generated by MySQL Workbench
-- qua 21 out 2020 15:33:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema she
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `she` ;

-- -----------------------------------------------------
-- Schema she
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `she` ;
USE `she` ;

-- -----------------------------------------------------
-- Table `she`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  `turno` INT NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `info_cadastro` VARCHAR(100) NULL DEFAULT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `curso_id` INT NOT NULL,
  `administrador_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  -- INDEX `curso_id` (`curso_id` ASC) VISIBLE,
  -- INDEX `administrador_id` (`administrador_id` ASC) VISIBLE,
  CONSTRAINT `aluno_ibfk_1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `she`.`curso` (`id`),
  CONSTRAINT `aluno_ibfk_2`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `she`.`administrador` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `she`.`dimensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`dimensao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `max_horas` INT NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `she`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `modo_comprovacao` VARCHAR(255) NULL DEFAULT NULL,
  `max_horas` INT NOT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `dimensao_id` INT NOT NULL,
  PRIMARY KEY (`id`)),
  -- INDEX `fk_atividade_dimensao1_idx` (`dimensao_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_dimensao1`
    FOREIGN KEY (`dimensao_id`)
    REFERENCES `she`.`dimensao` (`id`)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `she`.`aluno_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `she`.`aluno_atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `carga_horaria` TIME NOT NULL,
  `status` TINYINT NULL DEFAULT -1,
  `arquivo` VARCHAR(255) NOT NULL,
  `data_inicial` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `observacao` VARCHAR(1000) NULL,
  `motivo` VARCHAR(255) NULL,
  `aluno_id` INT NOT NULL,
  `atividade_id` INT NOT NULL,
  `administrador_id` INT NULL DEFAULT NULL,
  `data_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`, `aluno_id`, `atividade_id`),
  -- INDEX `atividade_id` (`atividade_id` ASC) VISIBLE,
  -- INDEX `aluno_id` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `aluno_atividade_ibfk_1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `she`.`atividade` (`id`),
  CONSTRAINT `aluno_atividade_ibfk_2`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `she`.`aluno` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Dados da Tabela Curso
INSERT INTO curso (nome, sigla, data_registro) VALUES ('Sistema da Informação', 'SI', DEFAULT);
INSERT INTO curso (nome, sigla, data_registro) VALUES ('Gestão Ambiental', 'GA', DEFAULT);

-- Dados da Tabela Administrador
INSERT INTO administrador (matricula, nome, email, senha, data_registro) VALUES ('123456789', 'Administrador', 'administrador@admin.com','e10adc3949ba59abbe56e057f20f883e', DEFAULT); 

--Dados da Tabela Dimensão
INSERT INTO dimensao(nome, max_horas) VALUES ('ENSINO', 60);
INSERT INTO dimensao(nome, max_horas) VALUES ('PESQUISA', 60);
INSERT INTO dimensao(nome, max_horas) VALUES ('EXTENSÃO', 60);
INSERT INTO dimensao(nome, max_horas) VALUES ('ATIVIDADES EXTRAS', 40);

-- Dados da Tabela Atividade
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Disciplinas cursadas além da grade regular do curso", "Secretaria Geral", 50, DEFAULT,1);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação de curso ministrado pela FAETERJ", "Coord. de Extensão", 40, DEFAULT,1);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Cursos externos correlatos ao curso do aluno", "Certificado do curso", 40, DEFAULT,1);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação como ouvinte em palestras correlatas ao curso do aluno", "Certificado da palestra / Ata de presença (quando realizada pela IES)", 10, DEFAULT,1);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Iniciação tecnológica e/ou científica", "Certificado", 40, DEFAULT,2);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Trabalhos publicados em periódicos científicos indexados", "Cópia do trabalho", 20, DEFAULT,2);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Trabalhos publicados em periódicos científicos não indexados", "Cópia do trabalho", 10, DEFAULT,2) ;
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Trabalhos apresentados em eventos científicos", "Certificado do evento e cópia do resumo", 10, DEFAULT,2);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação na publicação de capítulos de livros/revistas científicas", "Copia do trabalho", 10, DEFAULT,2);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação em pesquisa ou projetos institucionais na IES", "Coord. de Pesquisa", 20, DEFAULT,2);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Visita técnica", "Certificado / Ata de presença (quando realizada pela IES)", 20, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação como ouvinte em banca de TCC", "Ata de presença", 10, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação em projeto voltado para a comunidade e/ou de interesse da Instituição.", "Certificado / Comprovante ", 40, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Eventos acadêmicos promovidos por instituições/ órgãos oficiais relacionados à formação profissional do aluno", "Certificado", 15, DEFAULT,3) ;
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Representação estudantil em conselho, colegiado e diretório acadêmico.", "Direção ou Coord. de Curso", 15, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Atividades culturais: teatro, cinema, museu,  etc.", "Comprovante da Atividade", 10, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Ministrar curso na FAETERJ", "Certificado pela Coord. de Extensão", 30, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Monitoria (eventos na FAETERJ, externa, de disciplina concluída, de projeto)", "Declaração", 60, DEFAULT,3);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Apresentação de TCC", "Cópia da ata", 5, DEFAULT,4);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação em Empresa Junior", "Registro de posse em ata", 30, DEFAULT,4);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação em simulado promovido pela IES", "Ata de presença", 20, DEFAULT,4);
INSERT INTO atividade (nome, modo_comprovacao, max_horas, data_registro, dimensao_id) VALUES("Participação em avaliação institucional promovida pela IES", "Ata de presença", 20, DEFAULT,4);

-- Dados e Alunos Faker
-- Alunos Cadastrados
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000001','CARLA PITANGUI ALCANTARA NOGUEIRA','carla@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000002','ROSILANE CARLA SILVA YANOWICH','rosilane@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,2);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000003','VANESSA SOARES SIMÕES','vanessa@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000004','DANIELE RAMALHO DA SILVA SAMUEL','daniele@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,2);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000005','SAULO LIMA DA SILVA YANOWICH','saulo@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000006','NATHIANE DIAS IZABEL','nathiane@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000007','JOÃO ROBERTO DA SILVA DANTAS','joao@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,2);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000008','KARINA DO COUTO ALMEIDA','karina@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000009','EDILSON DOS SANTOS YATUHARA','edilson@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id) VALUES ('1220466000010','PRISCILA MONTEIRO SENRA DE OLIVEIRA', 'priscila@teste.com.br','e10adc3949ba59abbe56e057f20f883e',2,1);

-- alunos ativos
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000011','PRISCILA BARBOZA RODRIGUES','pbarbosa@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000012','DAYANE FERNANDES DA CUNHA BARRETO','dayabe@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000013','THAYNA DA SILVA TOME','thayna@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000014','GEOFFREY SOUZA DOS SANTOS','geoffrey@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000015','LUCIANA RIBEIRO DA SILVA','luciana@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000016','FABIANA THOMAZ MUNIZ','fabiana@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000017','MÁRIO SÉRGIO RODRIGUES DA SILVA','mario@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',1,1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000019','DEBORA LOPES DA SILVA PIRES','debora@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,1,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000010','LUCIANA BEATRIZ DE SOUZA SILVA','lbeatriz@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,2,1);
INSERT INTO aluno (matricula, nome, email, senha, turno, curso_id, status) VALUES ('1220466000020','ALEXANDRE ARAUJO DE JESUS','alexandre@teste.com.br', 'e10adc3949ba59abbe56e057f20f883e',2,2,1);

-- atividades cadastradas
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '01:00:00', -1, 'modelo.jpg', '2020-05-05', '2020-05-05', 11, 1);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '10:00:00', -1, 'modelo.jpg', '2020-06-01', '2020-06-20', 11, 3);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '00:30:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 11, 4);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '05:00:00', -1, 'modelo.jpg', '2020-08-15', '2020-08-15', 12, 5);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '03:00:00', -1, 'modelo.jpg', '2020-07-02', '2020-08-01', 12, 2);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '00:45:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 12, 1);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '04:00:00', -1, 'modelo.jpg', '2020-09-05', '2020-09-05', 13, 8);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '16:00:00', -1, 'modelo.jpg', '2020-09-02', '2020-09-09', 13, 5);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '02:30:00', -1, 'modelo.jpg', '2020-09-25', '2020-09-27', 13, 10);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '01:00:00', -1, 'modelo.jpg', '2020-05-05', '2020-05-05', 14, 1);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '10:00:00', -1, 'modelo.jpg', '2020-06-01', '2020-06-20', 14, 3);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '00:30:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 14, 4);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '05:00:00', -1, 'modelo.jpg', '2020-08-15', '2020-08-15', 15, 5);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '03:00:00', -1, 'modelo.jpg', '2020-07-02', '2020-08-01', 15, 2);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '00:45:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 15, 1);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '04:00:00', -1, 'modelo.jpg', '2020-09-05', '2020-09-05', 16, 8);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '16:00:00', -1, 'modelo.jpg', '2020-09-02', '2020-09-09', 16, 5);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '02:30:00', -1, 'modelo.jpg', '2020-09-25', '2020-09-27', 16, 10);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '01:00:00', -1, 'modelo.jpg', '2020-05-05', '2020-05-05', 17, 9);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '10:00:00', -1, 'modelo.jpg', '2020-06-01', '2020-06-20', 17, 3);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '00:30:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 17, 2);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '02:00:00', -1, 'modelo.jpg', '2020-08-15', '2020-08-15', 18, 11);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '01:00:00', -1, 'modelo.jpg', '2020-07-02', '2020-08-01', 18, 10);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '05:00:00', -1, 'modelo.jpg', '2020-07-01', '2020-07-01', 18, 4);

INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '20:00:00', -1, 'modelo.jpg', '2020-09-05', '2020-09-05', 19, 7);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '16:00:00', -1, 'modelo.jpg', '2020-09-02', '2020-09-09', 19, 6);
INSERT INTO aluno_atividade (descricao, carga_horaria, status, arquivo, data_inicial, data_final, aluno_id, atividade_id) VALUES ('Descrição da Atividade', '40:30:00', -1, 'modelo.jpg', '2020-09-25', '2020-09-27', 19, 10);